name: ESLint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "16.18.0"

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
            .eslintcache
            .stylelintcache
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: install dependecies
        run: yarn install --frozen-lockfile

      - name: lint
        run: yarn lint
